name: rl
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select
  - absl-py
  - aiohttp
  - anyio
  - argon2-cffi
  - astor
  - astunparse
  - async-timeout
  - async_generator
  - attrs
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - blas
  - bleach
  - blinker
  - bottleneck
  - brotli
  - brotlipy
  - ca-certificates
  - cachetools
  - certifi
  - cffi
  - chardet
  - charset-normalizer
  - click
  - colorama
  - coverage
  - cryptography
  - cycler
  - cython
  - dataclasses
  - debugpy
  - decorator
  - defusedxml
  - deprecation
  - entrypoints
  - fonttools
  - freetype
  - google-auth
  - google-auth-oauthlib
  - google-pasta
  - grpcio
  - h5py
  - hdf5
  - icc_rt
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter-packaging
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - keras
  - keras-applications
  - keras-base
  - keras-preprocessing
  - kiwisolver
  - libblas
  - libcblas
  - libpng
  - libprotobuf
  - libsodium
  - libtiff
  - lz4-c
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-gmp
  - m2w64-libwinpthread-git
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - msys2-conda-epoch
  - multidict
  - munkres
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - notebook
  - numexpr
  - oauthlib
  - olefile
  - openssl
  - opt_einsum
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pickleshare
  - pip
  - prometheus_client
  - prompt-toolkit
  - protobuf
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pygments
  - pyjwt
  - pyopenssl
  - pyparsing
  - pyqt
  - pyreadline
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pywin32
  - pywinpty
  - pyyaml
  - pyzmq
  - qt
  - requests
  - requests-oauthlib
  - rsa
  - scikit-learn
  - send2trash
  - setuptools
  - sip
  - six
  - sniffio
  - sqlite
  - tensorboard
  - tensorboard-plugin-wit
  - tensorflow
  - tensorflow-base
  - termcolor
  - terminado
  - testpath
  - threadpoolctl
  - tk
  - tomlkit
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - urllib3
  - vc
  - vs2015_runtime
  - wcwidth
  - webencodings
  - werkzeug
  - wheel
  - win_inet_pton
  - wincertstore
  - winpty
  - wrapt
  - xz
  - yaml
  - yarl
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - atari-py
    - cloudpickle
    - future
    - gast
    - gym
    - keras-rl
    - keras-rl2
    - numpy
    - opencv-python
    - pillow
    - psutil
    - pyglet
    - scipy
    - stable-baselines3
    - tensorflow-estimator
    - torch
